layout_spectrum: 0.7833184902556241
typography_spectrum: 0.33628063392825425
color:
  brandStrength: 0.22118117311038077
  lightness: 0.898459174670279
  saturation: 0.1640866892412305
  rhythmicContrast: 0.5691824359819293
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
author:
  name: Steve Abbott
  email: sabotproductions@gmail.com
  url: www.steveabbottauthor.com
name: Steve Abbott - Author
navigation:
  - name: More About Me...
    url: 'https://sabot03196.wordpress.com/about/'
    type: external
title: The Rough Draft
description: 'So many roads, so little time...'
