typography_spectrum: 0.968795598950237
color:
  brandStrength: 0.33049647929146886
  lightness: 0.0032576837111264467
  saturation: 0.6906369270291179
  rhythmicContrast: 0.024662632262334228
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
layout_spectrum: 0.7915720590390265
author:
  name: Steve Abbott
  email: sabotproductions@gmail.com
  url: www.steveabbottauthor.com
name: Steve Abbott - Author
navigation:
  - name: More About Me...
    url: 'https://sabot03196.wordpress.com/about/'
    type: external
title: The Rough Draft
description: 'So many roads, so little time...'
