typography_spectrum: 0.2849273046012968
color:
  brandStrength: 0.9700978603214025
  lightness: 0.8510752262081951
  saturation: 0.1350411707535386
  rhythmicContrast: 0.010458293603733182
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
layout_spectrum: 0.017327740555629134
author:
  name: Steve Abbott
  email: sabotproductions@gmail.com
  url: www.steveabbottauthor.com
name: Steve Abbott - Author
title: The Rough Draft
description: 'So many roads, so little time...'
